#Requires -Version 5.1
# ┌── APHOTIC CONTRACT ────────────────────────────────────────────────────────
# @task       T0.6
# @phase      0
# @status     DONE
# @spec       docs/GOLDEN-RULES.md (G2 G4 G5 G7) · docs/CONVENTIONS.md §2.6 · §3
# @spec       docs/BUILD-PLAN.md T0.6 (config wiring proof) · CLAUDE.md "BUILD & TEST COMMANDS"
# @rules      G2 G4 G5 G7
# @depends    nothing — pure PowerShell 5.1, no modules
# @facts      Gate list: g7 g4 g2 ids sdk purity transport todo all   (default = all)
# @facts      ALLOWED id homes (docs/CONVENTIONS.md §2.6): keeper/src/config.ts, app/src/config.ts,
# @facts        *.env / *.env.example, move/Move.toml. Plus two tooling exceptions, both
# @facts        documented inline: move/Move.lock + move/Published.toml (GENERATED by the Move
# @facts        package manager, carry upstream published-at ids) and the scripts/ verifiers
# @facts        themselves (they are the tools that PROVE those ids).
# @facts      ID PREFIXES watched: 0x5cdaebf264 0xfcea10ca 0x22c0ce66 0xf7152c05 0xd874d241
# @facts        0x22be4cad 0xfb28c4cb 0x243759 0xabf837 0x31358d 0xf9c0172b
# @facts      CODE vs COMMENT: a match inside a `//`, `#`, `/* */` comment or anywhere in a .md
# @facts        file is a NOTE, not a FAIL. Rationale: an APHOTIC CONTRACT banner that says
# @facts        "@forbidden use hashi:: in other modules" or "no Cetus (G4)" is the gate working,
# @facts        not a violation — failing on it trains everyone to ignore the gate. Pass -Strict
# @facts        for the literal "the string may not appear at all" behaviour.
# @implements Invoke-GateG7 · Invoke-GateG4 · Invoke-GateG2 · Invoke-GateIds
# @implements Invoke-GateSdk · Invoke-GatePurity · Invoke-GateTransport · Invoke-GateTodo
# @forbidden  crashing when move/, keeper/ or app/ does not exist — must report SKIP
# @invariant  1. Exit code is non-zero iff at least one gate is FAIL.
# @invariant  2. `todo` is informational and can never fail the run.
# @invariant  3. Every FAIL prints the offending <file>:<line>: <text>.
# @invariant  4. gates.sh produces the same verdicts on the same tree.
# @ac         runs clean on an empty tree (all SKIP) and on a fully scaffolded tree
# @verify     powershell -NoProfile -File scripts/gates.ps1 all
# @verify     powershell -NoProfile -File scripts/gates.ps1 all -Strict
# └── END CONTRACT ───────────────────────────────────────────────────────────

[CmdletBinding()]
param(
    [Parameter(Position = 0, ValueFromRemainingArguments = $true)]
    [string[]] $Gate
)

$ErrorActionPreference = 'Continue'
$RepoRoot = Split-Path -Parent $PSScriptRoot

# -Strict arrives through the remaining-args bag so `gates.ps1 all -Strict` works positionally.
$Strict = $false
if ($Gate) {
    $Gate = @($Gate | Where-Object {
            if ($_ -match '^-{1,2}strict$') { $script:Strict = $true; $false } else { $true }
        })
}

# Directories never scanned by any gate.
$ExcludeRx = '[\\/](node_modules|\.git|dist|build|coverage|\.vite|\.turbo|target|\.hashi_raw|\.hashi_src)[\\/]'

# ── file-name filters ────────────────────────────────────────────────────────
$RxMove = '\.move$'
$RxTs = '\.tsx?$'
$RxCode = '\.(move|ts|tsx|js|mjs|cjs)$'
$RxAnyText = '\.(move|ts|tsx|js|mjs|cjs|json|toml|lock|md|html|css|ps1|sh|yml|yaml)$|(^|\.)env(\.[A-Za-z0-9_.-]+)?$'

$HashCommentExt = @('.ps1', '.sh', '.toml', '.yml', '.yaml', '.lock')

# ── helpers ──────────────────────────────────────────────────────────────────
function Get-RelPath {
    param([string] $FullName)
    $rel = $FullName
    if ($FullName.StartsWith($RepoRoot, [System.StringComparison]::OrdinalIgnoreCase)) {
        $rel = $FullName.Substring($RepoRoot.Length).TrimStart('\', '/')
    }
    return ($rel -replace '\\', '/')
}

function Test-RootExists {
    param([string] $Rel)
    return (Test-Path -LiteralPath (Join-Path $RepoRoot $Rel))
}

function Get-GateFiles {
    param([string[]] $Roots, [string] $NameRegex)
    $out = New-Object System.Collections.ArrayList
    foreach ($r in $Roots) {
        $full = Join-Path $RepoRoot $r
        if (-not (Test-Path -LiteralPath $full)) { continue }
        $items = @(Get-ChildItem -LiteralPath $full -Recurse -File -Force -ErrorAction SilentlyContinue)
        foreach ($it in $items) {
            if ($it.FullName -match $ExcludeRx) { continue }
            if ($NameRegex -and ($it.Name -notmatch $NameRegex)) { continue }
            [void] $out.Add($it)
        }
    }
    return , $out.ToArray()
}

# Index at which a line's comment begins, or -1. `://` (URLs) is not a comment.
function Get-CommentStart {
    param([string] $Line, [string] $Ext)
    if ($Ext -eq '.md') { return 0 }
    $trim = $Line.TrimStart()
    if ($trim.StartsWith('*') -or $trim.StartsWith('/*')) { return 0 }
    $best = -1
    $m = [regex]::Match($Line, '(?<!:)//')
    if ($m.Success) { $best = $m.Index }
    if ($HashCommentExt -contains $Ext -or $Ext -eq '' -or $Ext -eq '.example') {
        $h = $Line.IndexOf('#')
        if ($h -ge 0 -and ($best -lt 0 -or $h -lt $best)) { $best = $h }
    }
    return $best
}

function Find-Hits {
    param([object[]] $Files, [string] $Regex, [string[]] $AllowRx = @())
    $hits = New-Object System.Collections.ArrayList
    foreach ($f in $Files) {
        $rel = Get-RelPath $f.FullName
        $skip = $false
        foreach ($a in $AllowRx) { if ($rel -match $a) { $skip = $true; break } }
        if ($skip) { continue }
        $lines = $null
        try { $lines = [System.IO.File]::ReadAllLines($f.FullName) } catch { continue }
        $ext = $f.Extension.ToLowerInvariant()
        for ($i = 0; $i -lt $lines.Length; $i++) {
            $m = [regex]::Match($lines[$i], $Regex, [System.Text.RegularExpressions.RegexOptions]::IgnoreCase)
            if (-not $m.Success) { continue }
            $cs = Get-CommentStart $lines[$i] $ext
            $isComment = ($cs -ge 0 -and $m.Index -ge $cs)
            [void] $hits.Add([pscustomobject]@{
                    Rel       = $rel
                    Line      = $i + 1
                    Text      = $lines[$i].Trim()
                    IsComment = $isComment
                })
        }
    }
    return , $hits.ToArray()
}

function New-Result {
    param([string] $Name, [string] $Title, [string] $Status, [object[]] $Hits = @(), [string] $Note = '', [object[]] $Notes = @())
    return [pscustomobject]@{ Name = $Name; Title = $Title; Status = $Status; Hits = $Hits; Note = $Note; Notes = $Notes }
}

function New-SkipOrVerdict {
    param([string] $Name, [string] $Title, [string[]] $Roots, [object[]] $Files, [object[]] $Hits, [string] $Note)
    $present = @($Roots | Where-Object { Test-RootExists $_ })
    if ($present.Count -eq 0) {
        return (New-Result $Name $Title 'SKIP' @() ("no scan root present: " + ($Roots -join ', ')))
    }
    $code = @($Hits | Where-Object { -not $_.IsComment })
    $comments = @($Hits | Where-Object { $_.IsComment })
    if ($Strict) { $code = @($Hits); $comments = @() }

    $scanned = "$($Files.Count) file(s) under $($present -join ', ')"
    if ($Note) { $scanned = "$scanned — $Note" }
    if ($comments.Count -gt 0) { $scanned = "$scanned · $($comments.Count) comment mention(s), not failing" }

    if ($code.Count -gt 0) { return (New-Result $Name $Title 'FAIL' $code $scanned $comments) }
    return (New-Result $Name $Title 'PASS' @() $scanned $comments)
}

# ── gates ────────────────────────────────────────────────────────────────────

# G7 — the entire Hashi Move surface is confined to gateway.move.
function Invoke-GateG7 {
    $roots = @('move/sources')
    $files = Get-GateFiles $roots $RxMove
    $allow = @('^move/sources/gateway\.move$')
    $hits = Find-Hits $files ([regex]::Escape('hashi::')) $allow
    return (New-SkipOrVerdict 'g7' 'Hashi isolation: `hashi::` only in move/sources/gateway.move' $roots $files $hits '')
}

# G4 — no Cetus / CLMM anywhere in the BTC vault.
function Invoke-GateG4 {
    $roots = @('move/sources', 'keeper/src')
    $files = Get-GateFiles $roots $RxCode
    $hits = Find-Hits $files 'cetus|clmm' @()
    return (New-SkipOrVerdict 'g4' 'No Cetus/CLMM under move/sources or keeper/src' $roots $files $hits '')
}

# G2 — the exit destination is never a parameter; it is read from the pinned on-chain value.
function Invoke-GateG2 {
    $roots = @('move/sources', 'keeper/src/execution')
    $moveFiles = Get-GateFiles @('move/sources') $RxMove
    $tsFiles = Get-GateFiles @('keeper/src/execution') $RxTs
    $hits = @()
    $hits += Find-Hits $moveFiles ([regex]::Escape('bitcoin_address')) @('^move/sources/gateway\.move$')
    $hits += Find-Hits $tsFiles ([regex]::Escape('bitcoinAddress')) @()
    $files = @($moveFiles) + @($tsFiles)
    return (New-SkipOrVerdict 'g2' 'No bitcoin-address parameter on any exit path' $roots $files $hits 'gateway.move exempt (it composes hashi::withdraw)')
}

# G7 (ids) — canonical on-chain ids live only in the sanctioned config homes.
function Invoke-GateIds {
    $roots = @('move', 'keeper', 'app', 'scripts')
    $files = Get-GateFiles $roots $RxAnyText
    $prefixes = @(
        '0x5cdaebf264', '0xfcea10ca', '0x22c0ce66', '0xf7152c05', '0xd874d241',
        '0x22be4cad', '0xfb28c4cb', '0x243759', '0xabf837', '0x31358d', '0xf9c0172b'
    )
    $rx = ($prefixes | ForEach-Object { [regex]::Escape($_) }) -join '|'
    $allow = @(
        '^keeper/src/config\.ts$',
        '^app/src/config\.ts$',
        '(^|/)\.env(\.[A-Za-z0-9_.-]+)?$',            # .env, .env.example, .env.local
        '^move/Move\.toml$',
        '^move/Move\.lock$',                          # generated: carries upstream published-at ids
        '^move/Published\.toml$',                     # generated by the Move package manager
        '^scripts/(verify-onchain\.mjs|gates\.ps1|gates\.sh|verify-all\.ps1)$'
    )
    $hits = Find-Hits $files $rx $allow
    return (New-SkipOrVerdict 'ids' 'Canonical ids only in config.ts / .env* / Move.toml' $roots $files $hits 'docs/ is out of scope by design')
}

# G7 (sdk) — the Hashi TypeScript SDK is reachable only through the real adapter.
function Invoke-GateSdk {
    $roots = @('keeper/src')
    $files = Get-GateFiles $roots $RxTs
    $allow = @('^keeper/src/hashi/real\.ts$')
    # IMPORT forms only (static / side-effect / dynamic import, require).
    $rx = "(from|import|require)\s*\(?\s*['`"]@mysten/hashi"
    $hits = Find-Hits $files $rx $allow
    return (New-SkipOrVerdict 'sdk' '@mysten/hashi imported only in keeper/src/hashi/real.ts' $roots $files $hits 'import forms only')
}

# G5 — evaluate()/route() must be pure so verify/ can replay them bit-for-bit.
function Invoke-GatePurity {
    $roots = @('keeper/src/strategy', 'keeper/src/routing')
    $files = Get-GateFiles $roots $RxTs
    $hits = Find-Hits $files 'Date\.now\s*\(|Math\.random\s*\(' @()
    return (New-SkipOrVerdict 'purity' 'No Date.now()/Math.random() in strategy/ or routing/' $roots $files $hits 'seeded jitter only')
}

# RECON R1 — exactly one Sui transport factory per surface.
function Invoke-GateTransport {
    $roots = @('keeper/src', 'app/src')
    $files = Get-GateFiles $roots $RxTs
    $allow = @('^keeper/src/sui/client\.ts$', '^app/src/lib/suiClient\.ts$')
    $hits = Find-Hits $files 'new\s+Sui(Grpc|JsonRpc)?Client\s*\(' $allow
    return (New-SkipOrVerdict 'transport' 'Sui client constructed only in sui/client.ts and lib/suiClient.ts' $roots $files $hits '')
}

# Informational census — never fails (docs/CONVENTIONS.md §3).
function Invoke-GateTodo {
    $roots = @('move', 'keeper', 'app', 'scripts')
    $present = @($roots | Where-Object { Test-RootExists $_ })
    if ($present.Count -eq 0) {
        return (New-Result 'todo' 'TODO(Tx.y) census' 'SKIP' @() ("no scan root present: " + ($roots -join ', ')))
    }
    $files = Get-GateFiles $roots $RxCode
    $tally = @{}
    $total = 0
    foreach ($f in $files) {
        $lines = $null
        try { $lines = [System.IO.File]::ReadAllLines($f.FullName) } catch { continue }
        foreach ($line in $lines) {
            foreach ($m in [regex]::Matches($line, 'TODO\(T\d+\.\d+\)')) {
                $id = $m.Value
                if ($tally.ContainsKey($id)) { $tally[$id] = $tally[$id] + 1 } else { $tally[$id] = 1 }
                $total++
            }
        }
    }
    $out = @()
    foreach ($k in ($tally.Keys | Sort-Object)) { $out += ("    {0,-14} {1}" -f $k, $tally[$k]) }
    $note = "$total marker(s) across $($tally.Keys.Count) task id(s) in $($files.Count) file(s) under $($present -join ', ')"
    return (New-Result 'todo' 'TODO(Tx.y) census (informational)' 'INFO' $out $note)
}

# ── dispatch ─────────────────────────────────────────────────────────────────
$Registry = [ordered]@{
    'g7'        = { Invoke-GateG7 }
    'g4'        = { Invoke-GateG4 }
    'g2'        = { Invoke-GateG2 }
    'ids'       = { Invoke-GateIds }
    'sdk'       = { Invoke-GateSdk }
    'purity'    = { Invoke-GatePurity }
    'transport' = { Invoke-GateTransport }
    'todo'      = { Invoke-GateTodo }
}

$requested = @()
if (-not $Gate -or $Gate.Count -eq 0) { $requested = @($Registry.Keys) }
else {
    foreach ($g in $Gate) {
        $key = $g.ToLowerInvariant().TrimStart('-')
        if ($key -eq 'all') { $requested = @($Registry.Keys); break }
        if ($key -eq 'help' -or $key -eq '?') {
            Write-Host "gates.ps1 [g7|g4|g2|ids|sdk|purity|transport|todo|all] [-Strict]   (default: all)"
            Write-Host "  -Strict  a match in a comment fails too (literal 'string must not appear')"
            exit 0
        }
        if (-not $Registry.Contains($key)) {
            Write-Host "gates.ps1: unknown gate '$g'. Known: $(($Registry.Keys) -join ', '), all" -ForegroundColor Red
            exit 2
        }
        $requested += $key
    }
}
$requested = @($requested | Select-Object -Unique)

Write-Host ''
Write-Host 'Aphotic x Hashi — golden-rule gates' -ForegroundColor Cyan
Write-Host "  repo   : $RepoRoot"
Write-Host "  mode   : $(if ($Strict) { 'STRICT (comment mentions fail)' } else { 'default (comment mentions are notes)' })"
Write-Host ''

$results = @()
foreach ($key in $requested) {
    $r = & $Registry[$key]
    $results += $r

    $color = 'Gray'
    if ($r.Status -eq 'PASS') { $color = 'Green' }
    elseif ($r.Status -eq 'FAIL') { $color = 'Red' }
    elseif ($r.Status -eq 'SKIP') { $color = 'Yellow' }
    elseif ($r.Status -eq 'INFO') { $color = 'Cyan' }

    Write-Host ("[{0}] {1,-10} {2}" -f $r.Status.PadRight(4), $r.Name, $r.Title) -ForegroundColor $color
    if ($r.Note) { Write-Host ("       {0}" -f $r.Note) -ForegroundColor DarkGray }

    if ($r.Status -eq 'FAIL') {
        foreach ($h in $r.Hits) {
            $text = $h.Text
            if ($text.Length -gt 140) { $text = $text.Substring(0, 137) + '...' }
            Write-Host ("    {0}:{1}: {2}" -f $h.Rel, $h.Line, $text) -ForegroundColor Red
        }
    }
    elseif ($r.Status -eq 'INFO') {
        foreach ($h in $r.Hits) { Write-Host $h -ForegroundColor DarkCyan }
    }

    foreach ($n in $r.Notes) {
        $text = $n.Text
        if ($text.Length -gt 120) { $text = $text.Substring(0, 117) + '...' }
        Write-Host ("    note {0}:{1}: {2}" -f $n.Rel, $n.Line, $text) -ForegroundColor DarkGray
    }
}

$failCount = @($results | Where-Object { $_.Status -eq 'FAIL' }).Count
$passCount = @($results | Where-Object { $_.Status -eq 'PASS' }).Count
$skipCount = @($results | Where-Object { $_.Status -eq 'SKIP' }).Count

Write-Host ''
Write-Host ("  {0} PASS · {1} FAIL · {2} SKIP" -f $passCount, $failCount, $skipCount) -ForegroundColor $(if ($failCount -gt 0) { 'Red' } else { 'Green' })
Write-Host ''

if ($failCount -gt 0) { exit 1 }
exit 0
