#Requires -Version 5.1
# ┌── APHOTIC CONTRACT ────────────────────────────────────────────────────────
# @task       T0.6 (v2 retarget)
# @phase      0
# @status     DONE
# @spec       CLAUDE.md "THE 10 GOLDEN RULES" (G2 G3 G7 G9) · docs/CONVENTIONS.md §2.6 · §6
# @spec       docs/DESIGN-V2.md §7 (INV-C1 + the complete KeeperCap surface) · §10 (the gate rows)
# @spec       docs/DESIGN-V2.md §1 F1 (the Seal LE/BE trap) · §8 D12 (B11) · §11 (the notes ladder)
# @rules      G3 (no keeper-nameable destination) · G5 (monotonic, mechanical state)
# @rules      G6 (the Seal identity is LITTLE-ENDIAN) · G7 (one implementation; ids as config)
# @rules      G9 (no Note carries an amount) · G10 (edition idioms)
# @depends    nothing — pure PowerShell 5.1, no modules
# @facts      Gate list (13):
# @facts        g7 g4 g2 ids sdk purity transport notes batchstate keepercap send seal_le todo
# @facts        default = all.  `all` and `-Strict` are positional.
# @facts      ⚠ THE PRODUCT PIVOTED. gateway.move / router.move / journal.move / the old
# @facts        vault.move are DELETED. The Hashi Move boundary is now `carry.move`; the new
# @facts        modules are caps vault notes balance batch clearing allocate carry oracle events.
# @facts      A gate whose TARGET FILE does not exist yet reports SKIP with the reason spelled
# @facts        out, and SKIP is counted separately from PASS. A gate must never look green
# @facts        because the thing it protects has not been written yet.
# @facts      ALLOWED id homes (docs/CONVENTIONS.md §2.6): keeper/src/config.ts, sdk/src/config.ts,
# @facts        app/src/config.ts, *.env / *.env.example, move/Move.toml. Plus two tooling
# @facts        exceptions, both documented inline: move/Move.lock + move/Published.toml
# @facts        (GENERATED by the Move package manager, carry upstream published-at ids) and the
# @facts        scripts/ verifiers themselves (they are the tools that PROVE those ids).
# @facts      ID PREFIXES watched: 0x5cdaebf264 0xfcea10ca 0x22c0ce66 0xf7152c05 0xd874d241
# @facts        0x22be4cad 0xfb28c4cb 0x243759 0xabf837 0x31358d 0xf9c0172b
# @facts      CODE vs COMMENT: a match inside a `//`, `#`, `/* */` comment or anywhere in a .md
# @facts        file is a NOTE, not a FAIL. Rationale: an APHOTIC CONTRACT banner that says
# @facts        "@forbidden use hashi:: in other modules" or "no Cetus (G4)" is the gate working,
# @facts        not a violation — failing on it trains everyone to ignore the gate. Pass -Strict
# @facts        for the literal "the string may not appear at all" behaviour.
# @implements Invoke-GateG7 · Invoke-GateG4 · Invoke-GateG2 · Invoke-GateIds
# @implements Invoke-GateSdk · Invoke-GatePurity · Invoke-GateTransport
# @implements Invoke-GateNotes · Invoke-GateBatchState · Invoke-GateKeeperCap
# @implements Invoke-GateSend · Invoke-GateSealLe · Invoke-GateTodo
# @forbidden  crashing when move/, keeper/, sdk/ or app/ does not exist — must report SKIP
# @forbidden  counting SKIP as green anywhere in the summary
# @invariant  1. Exit code is non-zero iff at least one gate is FAIL.
# @invariant  2. `todo` is informational and can never fail the run.
# @invariant  3. Every FAIL prints the offending <file>:<line>: <text>.
# @invariant  4. gates.sh produces the same verdicts on the same tree.
# @invariant  5. A missing target is SKIP with a stated reason, never PASS.
# @ac         runs clean on an empty tree (all SKIP) and on a fully scaffolded tree
# @verify     powershell -NoProfile -File scripts/gates.ps1 all
# @verify     powershell -NoProfile -File scripts/gates.ps1 all -Strict
# @verify     bash scripts/gates.sh all        # must agree, verdict for verdict
# └── END CONTRACT ───────────────────────────────────────────────────────────

[CmdletBinding()]
param(
    [Parameter(Position = 0, ValueFromRemainingArguments = $true)]
    [string[]] $Gate
)

$ErrorActionPreference = 'Continue'
$RepoRoot = Split-Path -Parent $PSScriptRoot

# -Strict arrives through the remaining-args bag so `gates.ps1 all -Strict` works positionally.
$Strict = $false
if ($Gate) {
    $Gate = @($Gate | Where-Object {
            if ($_ -match '^-{1,2}strict$') { $script:Strict = $true; $false } else { $true }
        })
}

# Directories never scanned by any gate.
$ExcludeRx = '[\\/](node_modules|\.git|dist|build|coverage|\.vite|\.turbo|target|\.hashi_raw|\.hashi_src)[\\/]'

# ── file-name filters ────────────────────────────────────────────────────────
$RxMove = '\.move$'
$RxTs = '\.tsx?$'
$RxCode = '\.(move|ts|tsx|js|mjs|cjs)$'
$RxAnyText = '\.(move|ts|tsx|js|mjs|cjs|json|toml|lock|md|html|css|ps1|sh|yml|yaml)$|(^|\.)env(\.[A-Za-z0-9_.-]+)?$'

$HashCommentExt = @('.ps1', '.sh', '.toml', '.yml', '.yaml', '.lock')

# ── the v2 module map (docs/DESIGN-V2.md) ────────────────────────────────────
$CarryMove = 'move/sources/carry.move'      # THE Hashi boundary (was gateway.move)
$NotesMove = 'move/sources/notes.move'
$BatchMove = 'move/sources/batch.move'
$SendTs = 'keeper/src/sui/send.ts'          # THE devInspect-then-send wrapper

# docs/DESIGN-V2.md §7 — the COMPLETE keeper-callable list. INV-C1 is enforced by the
# ABSENCE of an address parameter, so this list and the grep are the whole enforcement.
$KeeperCallable = @('propose_nav', 'attest_limiter', 'allocate', 'deallocate',
    'place_carry_bid', 'cancel_carry_bid', 'settle_step')

# ── helpers ──────────────────────────────────────────────────────────────────
function Get-RelPath {
    param([string] $FullName)
    $rel = $FullName
    if ($FullName.StartsWith($RepoRoot, [System.StringComparison]::OrdinalIgnoreCase)) {
        $rel = $FullName.Substring($RepoRoot.Length).TrimStart('\', '/')
    }
    return ($rel -replace '\\', '/')
}

function Test-RootExists {
    param([string] $Rel)
    return (Test-Path -LiteralPath (Join-Path $RepoRoot $Rel))
}

function Get-GateFiles {
    param([string[]] $Roots, [string] $NameRegex)
    $out = New-Object System.Collections.ArrayList
    foreach ($r in $Roots) {
        $full = Join-Path $RepoRoot $r
        if (-not (Test-Path -LiteralPath $full)) { continue }
        $items = @(Get-ChildItem -LiteralPath $full -Recurse -File -Force -ErrorAction SilentlyContinue)
        foreach ($it in $items) {
            if ($it.FullName -match $ExcludeRx) { continue }
            if ($NameRegex -and ($it.Name -notmatch $NameRegex)) { continue }
            [void] $out.Add($it)
        }
    }
    return , $out.ToArray()
}

# Index at which a line's comment begins, or -1. `://` (URLs) is not a comment.
function Get-CommentStart {
    param([string] $Line, [string] $Ext)
    if ($Ext -eq '.md') { return 0 }
    $trim = $Line.TrimStart()
    if ($trim.StartsWith('*') -or $trim.StartsWith('/*')) { return 0 }
    $best = -1
    $m = [regex]::Match($Line, '(?<!:)//')
    if ($m.Success) { $best = $m.Index }
    if ($HashCommentExt -contains $Ext -or $Ext -eq '' -or $Ext -eq '.example') {
        $h = $Line.IndexOf('#')
        if ($h -ge 0 -and ($best -lt 0 -or $h -lt $best)) { $best = $h }
    }
    return $best
}

# Comment-blanked view of a file, LINE NUMBERING PRESERVED. Mirrors gates.sh `decomment`.
# The structural gates (notes / batchstate / keepercap / seal_le) parse this, never the raw
# text, so a banner that quotes the forbidden shape is not mistaken for the shape itself.
function Get-CodeLines {
    param([string] $FullPath)
    $lines = @()
    try { $lines = [System.IO.File]::ReadAllLines($FullPath) } catch { return @() }
    $out = New-Object string[] $lines.Length
    for ($i = 0; $i -lt $lines.Length; $i++) {
        $l = $lines[$i]
        if ($l.TrimStart().StartsWith('*')) { $out[$i] = ''; continue }
        $l = [regex]::Replace($l, '(?<!:)//.*$', '')
        $l = [regex]::Replace($l, '/\*.*$', '')
        $out[$i] = $l
    }
    return $out
}

function Find-Hits {
    param([object[]] $Files, [string] $Regex, [string[]] $AllowRx = @())
    $hits = New-Object System.Collections.ArrayList
    foreach ($f in $Files) {
        $rel = Get-RelPath $f.FullName
        $skip = $false
        foreach ($a in $AllowRx) { if ($rel -match $a) { $skip = $true; break } }
        if ($skip) { continue }
        $lines = $null
        try { $lines = [System.IO.File]::ReadAllLines($f.FullName) } catch { continue }
        $ext = $f.Extension.ToLowerInvariant()
        for ($i = 0; $i -lt $lines.Length; $i++) {
            $m = [regex]::Match($lines[$i], $Regex, [System.Text.RegularExpressions.RegexOptions]::IgnoreCase)
            if (-not $m.Success) { continue }
            $cs = Get-CommentStart $lines[$i] $ext
            $isComment = ($cs -ge 0 -and $m.Index -ge $cs)
            [void] $hits.Add([pscustomobject]@{
                    Rel       = $rel
                    Line      = $i + 1
                    Text      = $lines[$i].Trim()
                    IsComment = $isComment
                })
        }
    }
    return , $hits.ToArray()
}

function New-Result {
    param([string] $Name, [string] $Title, [string] $Status, [object[]] $Hits = @(), [string] $Note = '', [object[]] $Notes = @())
    return [pscustomobject]@{ Name = $Name; Title = $Title; Status = $Status; Hits = $Hits; Note = $Note; Notes = $Notes }
}

function New-Hit {
    param([string] $Rel, [int] $Line, [string] $Text)
    return [pscustomobject]@{ Rel = $Rel; Line = $Line; Text = $Text; IsComment = $false }
}

function New-SkipOrVerdict {
    param([string] $Name, [string] $Title, [string[]] $Roots, [object[]] $Files, [object[]] $Hits, [string] $Note)
    $present = @($Roots | Where-Object { Test-RootExists $_ })
    if ($present.Count -eq 0) {
        return (New-Result $Name $Title 'SKIP' @() ("NOTHING CHECKED — no scan root present: " + ($Roots -join ', ')))
    }
    $code = @($Hits | Where-Object { -not $_.IsComment })
    $comments = @($Hits | Where-Object { $_.IsComment })
    if ($Strict) { $code = @($Hits); $comments = @() }

    $scanned = "$($Files.Count) file(s) under $($present -join ', ')"
    if ($Note) { $scanned = "$scanned — $Note" }
    if ($comments.Count -gt 0) { $scanned = "$scanned · $($comments.Count) comment mention(s), not failing" }

    if ($code.Count -gt 0) { return (New-Result $Name $Title 'FAIL' $code $scanned $comments) }
    return (New-Result $Name $Title 'PASS' @() $scanned $comments)
}

# ── gates ────────────────────────────────────────────────────────────────────

# G7 — the entire Hashi Move surface is confined to carry.move (v2: was gateway.move).
function Invoke-GateG7 {
    $roots = @('move/sources')
    $files = Get-GateFiles $roots $RxMove
    $allow = @('^' + [regex]::Escape($CarryMove) + '$')
    $hits = Find-Hits $files ([regex]::Escape('hashi::')) $allow
    $note = if (Test-RootExists $CarryMove) { "$CarryMove is the sole exempt file" }
    else { "⚠ $CarryMove DOES NOT EXIST YET — nothing is exempt, so any hashi:: reference anywhere fails" }
    return (New-SkipOrVerdict 'g7' "Hashi isolation: ``hashi::`` only in $CarryMove" $roots $files $hits $note)
}

# G4 — no Cetus / CLMM anywhere in the BTC vault.
function Invoke-GateG4 {
    $roots = @('move/sources', 'keeper/src')
    $files = Get-GateFiles $roots $RxCode
    $hits = Find-Hits $files 'cetus|clmm' @()
    return (New-SkipOrVerdict 'g4' 'No Cetus/CLMM under move/sources or keeper/src' $roots $files $hits '')
}

# G2 / INV-C1 — the exit destination is never a parameter; it is read from the pinned
# on-chain value. Two independent checks:
#   (a) `bitcoin_address` may appear only in carry.move (it composes hashi::withdraw)
#   (b) `exit_to_bitcoin`, WHEREVER it is declared — carry.move included, NO exemption —
#       must not take a destination parameter. (a) alone cannot catch that, because
#       carry.move is exempt from (a) by construction.
function Invoke-GateG2 {
    $roots = @('move/sources', 'keeper/src/execution', 'sdk/src/execution')
    $moveFiles = Get-GateFiles @('move/sources') $RxMove
    $tsFiles = Get-GateFiles @('keeper/src/execution', 'sdk/src/execution') $RxTs
    $hits = @()
    $hits += Find-Hits $moveFiles ([regex]::Escape('bitcoin_address')) @('^' + [regex]::Escape($CarryMove) + '$')
    $hits += Find-Hits $tsFiles ([regex]::Escape('bitcoinAddress')) @()

    # (b) the signature check — no exemption anywhere.
    $declared = 0
    foreach ($f in $moveFiles) {
        $rel = Get-RelPath $f.FullName
        foreach ($sig in (Get-FnSignatures $f.FullName 'exit_to_bitcoin')) {
            $declared++
            if (Test-ParamListNamesADestination $sig.Params) {
                $hits += (New-Hit $rel $sig.Line ("exit_to_bitcoin takes a destination parameter: (" + ($sig.Params -replace '\s+', ' ').Trim() + ")"))
            }
        }
    }
    $files = @($moveFiles) + @($tsFiles)
    $note = "$CarryMove exempt from the bitcoin_address scan (it composes hashi::withdraw); the exit_to_bitcoin signature check is NOT exempt"
    if ($declared -eq 0) { $note = "$note · no exit_to_bitcoin declared yet, so the signature check inspected nothing" }
    else { $note = "$note · $declared exit_to_bitcoin declaration(s) inspected" }
    return (New-SkipOrVerdict 'g2' 'No bitcoin-address parameter on any exit path' $roots $files $hits $note)
}

# G7 (ids) — canonical on-chain ids live only in the sanctioned config homes.
function Invoke-GateIds {
    $roots = @('move', 'keeper', 'sdk', 'app', 'scripts')
    $files = Get-GateFiles $roots $RxAnyText
    $prefixes = @(
        '0x5cdaebf264', '0xfcea10ca', '0x22c0ce66', '0xf7152c05', '0xd874d241',
        '0x22be4cad', '0xfb28c4cb', '0x243759', '0xabf837', '0x31358d', '0xf9c0172b'
    )
    $rx = ($prefixes | ForEach-Object { [regex]::Escape($_) }) -join '|'
    $allow = @(
        '^keeper/src/config\.ts$',
        '^sdk/src/config\.ts$',
        '^app/src/config\.ts$',
        '(^|/)\.env(\.[A-Za-z0-9_.-]+)?$',            # .env, .env.example, .env.local
        '^move/Move\.toml$',
        '^move/Move\.lock$',                          # generated: carries upstream published-at ids
        '^move/Published\.toml$',                     # generated by the Move package manager
        '^scripts/(verify-onchain\.mjs|gates\.ps1|gates\.sh|verify-all\.ps1)$'
    )
    $hits = Find-Hits $files $rx $allow
    return (New-SkipOrVerdict 'ids' 'Canonical ids only in config.ts / .env* / Move.toml' $roots $files $hits 'docs/ is out of scope by design')
}

# G7 (sdk) — the Hashi TypeScript SDK is reachable only through the real adapter.
function Invoke-GateSdk {
    $roots = @('keeper/src', 'sdk/src')
    $files = Get-GateFiles $roots $RxTs
    $allow = @('^keeper/src/hashi/real\.ts$', '^sdk/src/hashi/real\.ts$')
    # IMPORT forms only (static / side-effect / dynamic import, require).
    $rx = "(from|import|require)\s*\(?\s*['`"]@mysten/hashi"
    $hits = Find-Hits $files $rx $allow
    return (New-SkipOrVerdict 'sdk' '@mysten/hashi imported only in {keeper,sdk}/src/hashi/real.ts' $roots $files $hits 'import forms only')
}

# G5 — evaluate()/route()/clearing must be pure so verify/ and the Move twin can replay them
# bit-for-bit. sdk/ is in scope because DESIGN-V2 §9 puts clearing, the Merkle tree and the
# Seal identity encoder there, and all three are release-gated on byte-for-byte parity.
function Invoke-GatePurity {
    $roots = @('keeper/src/strategy', 'keeper/src/routing', 'sdk/src')
    $files = Get-GateFiles $roots $RxTs
    $hits = Find-Hits $files 'Date\.now\s*\(|Math\.random\s*\(' @()
    return (New-SkipOrVerdict 'purity' 'No Date.now()/Math.random() in strategy/, routing/ or sdk/' $roots $files $hits 'seeded jitter only')
}

# RECON R1 — exactly one Sui transport factory per surface.
function Invoke-GateTransport {
    $roots = @('keeper/src', 'sdk/src', 'app/src')
    $files = Get-GateFiles $roots $RxTs
    $allow = @('^keeper/src/sui/client\.ts$', '^sdk/src/sui/client\.ts$', '^app/src/lib/suiClient\.ts$')
    $hits = Find-Hits $files 'new\s+Sui(Grpc|JsonRpc)?Client\s*\(' $allow
    return (New-SkipOrVerdict 'transport' 'Sui client constructed only in sui/client.ts and lib/suiClient.ts' $roots $files $hits '')
}

# ── v2 structural gates ──────────────────────────────────────────────────────

# DESIGN-V2 §10 Notes — `struct Note` may declare NOTHING but `id` and `denom_index`.
# A `Balance`, an `amount`, or any other field would leak order size out of escrow no matter
# what is encrypted on top; the denomination ladder (§11) exists precisely so the struct can
# be this empty. `denom_index` is an index INTO the ladder, not a value.
function Invoke-GateNotes {
    $title = '`struct Note` declares only id + denom_index (no amount can leak)'
    $full = Join-Path $RepoRoot $NotesMove
    if (-not (Test-Path -LiteralPath $full)) {
        return (New-Result 'notes' $title 'SKIP' @() "NOTHING CHECKED — $NotesMove does not exist yet (v2 notes module has not landed)")
    }
    $lines = Get-CodeLines $full
    $hits = New-Object System.Collections.ArrayList
    $fields = @()
    $state = 0   # 0 = looking, 2 = decl seen / awaiting '{', 1 = inside body, 3 = done
    for ($i = 0; $i -lt $lines.Length -and $state -ne 3; $i++) {
        $l = $lines[$i]
        if ($state -eq 0) {
            if ($l -match 'struct\s+Note\b\s+has') { $state = if ($l -match '\{') { 1 } else { 2 } }
            continue
        }
        if ($state -eq 2) { if ($l -match '\{') { $state = 1 }; continue }
        # inside the body
        if ($l -match '\}') { $state = 3; continue }
        $t = $l.Trim()
        if (-not $t) { continue }
        $idx = $t.IndexOf(':')
        if ($idx -lt 1) { continue }
        $name = ($t.Substring(0, $idx) -replace '\s', '')
        $fields += $name
        if ($name -ne 'id' -and $name -ne 'denom_index') {
            [void] $hits.Add((New-Hit $NotesMove ($i + 1) $t))
        }
    }
    if ($state -eq 0) {
        return (New-Result 'notes' $title 'SKIP' @() "NOTHING CHECKED — $NotesMove exists but declares no ``struct Note``")
    }
    $note = "$NotesMove · fields found: " + $(if ($fields.Count) { $fields -join ', ' } else { '(none)' })
    if ($hits.Count -gt 0) { return (New-Result 'notes' $title 'FAIL' $hits.ToArray() "$note — a Note field other than id/denom_index leaks size out of escrow") }
    return (New-Result 'notes' $title 'PASS' @() $note)
}

# DESIGN-V2 §10 Batch — `.state =` may be written ONLY inside `set_state` and inside the
# struct literal built by `open_batch`. That single funnel is what makes
# OPEN -> SEALED -> CLEARING -> SETTLED provably monotonic: the assertions live in one
# function, so no other code path can move the machine sideways or backwards.
function Invoke-GateBatchState {
    $title = '`.state =` only inside set_state / open_batch (monotonic transitions)'
    $full = Join-Path $RepoRoot $BatchMove
    if (-not (Test-Path -LiteralPath $full)) {
        return (New-Result 'batchstate' $title 'SKIP' @() "NOTHING CHECKED — $BatchMove does not exist yet (v2 batch module has not landed)")
    }
    $lines = Get-CodeLines $full
    $hits = New-Object System.Collections.ArrayList
    $allow = $false; $pending = $false; $depth = 0; $writes = 0
    for ($i = 0; $i -lt $lines.Length; $i++) {
        $raw = $lines[$i]
        if (-not $allow -and -not $pending -and $raw -match 'fun\s+(set_state|open_batch)\s*[(<]') { $pending = $true }
        $ob = ([regex]::Matches($raw, '\{')).Count
        $cb = ([regex]::Matches($raw, '\}')).Count
        $wasAllowed = ($allow -or $pending)
        if ($pending -and $ob -gt 0) {
            $allow = $true; $pending = $false; $depth = $ob - $cb
            if ($depth -le 0) { $allow = $false }
        }
        elseif ($allow) {
            $depth += ($ob - $cb)
            if ($depth -le 0) { $allow = $false }
        }
        if ($raw -match '\.state\s*=(?!=)') {
            $writes++
            if (-not $wasAllowed) { [void] $hits.Add((New-Hit $BatchMove ($i + 1) $raw.Trim())) }
        }
    }
    $note = "$BatchMove · $writes ``.state =`` write(s) total, $($hits.Count) outside set_state/open_batch"
    if ($hits.Count -gt 0) { return (New-Result 'batchstate' $title 'FAIL' $hits.ToArray() $note) }
    return (New-Result 'batchstate' $title 'PASS' @() $note)
}

# ── Move signature parsing (shared by g2 and keepercap) ──────────────────────
# Returns every declaration of `fun <Name>` in a file with its PARAMETER LIST only — the
# text between the parenthesis that follows the function name and its match. Starting the
# scan at the function name (not at the first `(` in the line) is what keeps
# `public(package) fun allocate(...)` from being read as `(package)`; stopping at the
# matching close is what keeps a `: (u64, address)` RETURN TYPE out of the parameter list.
function Get-FnSignatures {
    param([string] $FullPath, [string] $Name)
    $out = @()
    $lines = Get-CodeLines $FullPath
    $rx = 'fun\s+' + [regex]::Escape($Name) + '\s*[(<]'
    for ($i = 0; $i -lt $lines.Length; $i++) {
        $m = [regex]::Match($lines[$i], $rx)
        if (-not $m.Success) { continue }
        # Accumulate from the function name forward until the parentheses balance.
        $buf = $lines[$i].Substring($m.Index)
        $j = $i
        while ($true) {
            $params = Get-ParamList $buf
            if ($null -ne $params) { $out += [pscustomobject]@{ Line = $i + 1; Params = $params }; break }
            $j++
            if ($j -ge $lines.Length -or ($j - $i) -gt 60) { break }
            $buf += "`n" + $lines[$j]
        }
    }
    return , $out
}

# Text between the first '(' and its matching ')', or $null if not yet balanced.
function Get-ParamList {
    param([string] $Text)
    $start = $Text.IndexOf('(')
    if ($start -lt 0) { return $null }
    $d = 0
    $sb = New-Object System.Text.StringBuilder
    for ($k = $start; $k -lt $Text.Length; $k++) {
        $c = $Text[$k]
        if ($c -eq '(') { $d++; if ($d -eq 1) { continue } }
        elseif ($c -eq ')') { $d--; if ($d -eq 0) { return $sb.ToString() } }
        if ($d -ge 1) { [void] $sb.Append($c) }
    }
    return $null
}

# INV-C1 (keepercap): does this parameter list name the `address` TYPE anywhere — bare, in a
# vector, in an Option, behind a reference? A keeper that cannot name a destination cannot send
# funds to one, so the whole invariant is "the word does not appear". Word-bounded, so a
# `&AdapterRegistry` or a `venue: ID` is not a false positive.
function Test-ParamListNamesAnAddressType {
    param([string] $Params)
    if ($null -eq $Params) { return $false }
    return ($Params -match '(^|[^A-Za-z0-9_])address([^A-Za-z0-9_]|$)')
}

# G2 (exit_to_bitcoin): strictly BROADER than the INV-C1 test, and deliberately so. The
# destination is read from the vault's pinned value, so NO parameter of this function may
# name a destination in any form — including `bitcoin_address: vector<u8>`, which the
# word-bounded test above misses because `_address` is one identifier.
function Test-ParamListNamesADestination {
    param([string] $Params)
    if ($null -eq $Params) { return $false }
    return ($Params -match '(?i)address|recipient|destination|payout_to|send_to')
}

# DESIGN-V2 §7 / INV-C1 — no KeeperCap-gated function may take an `address` parameter.
# The invariant is enforced by the ABSENCE of the parameter, which is exactly why a grep
# is the right enforcement and not a weak proxy for one.
function Invoke-GateKeeperCap {
    $title = 'No KeeperCap-gated function takes an address parameter (INV-C1)'
    $roots = @('move/sources')
    if (-not (Test-RootExists 'move/sources')) {
        return (New-Result 'keepercap' $title 'SKIP' @() 'NOTHING CHECKED — no scan root present: move/sources')
    }
    $files = Get-GateFiles $roots $RxMove
    $hits = New-Object System.Collections.ArrayList
    $found = @(); $missing = @()
    foreach ($name in $KeeperCallable) {
        $any = $false
        foreach ($f in $files) {
            $rel = Get-RelPath $f.FullName
            foreach ($sig in (Get-FnSignatures $f.FullName $name)) {
                $any = $true
                if (Test-ParamListNamesAnAddressType $sig.Params) {
                    [void] $hits.Add((New-Hit $rel $sig.Line ("$name takes an address parameter: (" + ($sig.Params -replace '\s+', ' ').Trim() + ")")))
                }
            }
        }
        if ($any) { $found += $name } else { $missing += $name }
    }
    if ($found.Count -eq 0) {
        return (New-Result 'keepercap' $title 'SKIP' @() ("NOTHING CHECKED — none of the 7 keeper-callable functions is declared yet: " + ($KeeperCallable -join ', ')))
    }
    $note = "checked: " + ($found -join ', ')
    if ($missing.Count -gt 0) { $note = "$note · NOT YET DECLARED (unchecked): " + ($missing -join ', ') }
    if ($hits.Count -gt 0) { return (New-Result 'keepercap' $title 'FAIL' $hits.ToArray() $note) }
    return (New-Result 'keepercap' $title 'PASS' @() $note)
}

# Every transaction goes through the devInspect-then-send wrapper, so a transaction that
# would revert is never broadcast. `signAndExecute` outside that one file means some path
# can broadcast blind.
function Invoke-GateSend {
    $title = 'signAndExecute only in ' + $SendTs + ' (devInspect-then-send)'
    $roots = @('keeper/src', 'sdk/src')
    if (-not (Test-Path -LiteralPath (Join-Path $RepoRoot $SendTs))) {
        return (New-Result 'send' $title 'SKIP' @() "NOTHING CHECKED — $SendTs does not exist yet, so there is no wrapper to funnel through (v2 keeper has not landed)")
    }
    $files = Get-GateFiles $roots $RxTs
    $allow = @('^' + [regex]::Escape($SendTs) + '$')
    # (?-i) forces CASE SENSITIVITY — PowerShell regex is case-insensitive by default,
    # so the bare word also matched the TYPE `SignAndExecute` and the injected field
    # `readonly signAndExecute?: SignAndExecute`. Neither is a call site, and flagging
    # them made the gate cry wolf on dependency injection.
    # `\s*\(` narrows it to an actual invocation, which is the only thing that can
    # broadcast a transaction without going through the devInspect wrapper.
    $hits = Find-Hits $files '(?-i)\bsignAndExecute\s*\(' $allow
    return (New-SkipOrVerdict 'send' $title $roots $files $hits 'a revert must never be broadcast')
}

# DESIGN-V2 §1 F1 — the deleted vault.move decoded the Seal identity epoch BIG-ENDIAN
# (`epoch = (epoch << 8) + byte`) while `bcs::peel_u64` reads LITTLE-ENDIAN. Copying that
# forward yields a policy that never opens, and it fails SILENTLY: the key server simply
# declines and the batch never reveals. Structural twin of the RECON R14 txid trap.
function Invoke-GateSealLe {
    $title = 'No big-endian u64 decode (`<< 8`) in ' + $BatchMove + ' (Seal identity is LE)'
    $full = Join-Path $RepoRoot $BatchMove
    if (-not (Test-Path -LiteralPath $full)) {
        return (New-Result 'seal_le' $title 'SKIP' @() "NOTHING CHECKED — $BatchMove does not exist yet (v2 batch module has not landed)")
    }
    $lines = Get-CodeLines $full
    $hits = New-Object System.Collections.ArrayList
    for ($i = 0; $i -lt $lines.Length; $i++) {
        if ($lines[$i] -match '<<\s*8\b') { [void] $hits.Add((New-Hit $BatchMove ($i + 1) $lines[$i].Trim())) }
    }
    $note = "$BatchMove · use bcs::peel_u64 (LITTLE-ENDIAN); see DESIGN-V2 §1 F1 and §3"
    if ($hits.Count -gt 0) { return (New-Result 'seal_le' $title 'FAIL' $hits.ToArray() $note) }
    return (New-Result 'seal_le' $title 'PASS' @() $note)
}

# Informational census — never fails (docs/CONVENTIONS.md §3).
function Invoke-GateTodo {
    $roots = @('move', 'keeper', 'sdk', 'app', 'scripts')
    $present = @($roots | Where-Object { Test-RootExists $_ })
    if ($present.Count -eq 0) {
        return (New-Result 'todo' 'TODO(Tx.y) census' 'SKIP' @() ("NOTHING CHECKED — no scan root present: " + ($roots -join ', ')))
    }
    $files = Get-GateFiles $roots $RxCode
    $tally = @{}
    $total = 0
    foreach ($f in $files) {
        $lines = $null
        try { $lines = [System.IO.File]::ReadAllLines($f.FullName) } catch { continue }
        foreach ($line in $lines) {
            foreach ($m in [regex]::Matches($line, 'TODO\(T\d+\.\d+\)')) {
                $id = $m.Value
                if ($tally.ContainsKey($id)) { $tally[$id] = $tally[$id] + 1 } else { $tally[$id] = 1 }
                $total++
            }
        }
    }
    $out = @()
    foreach ($k in ($tally.Keys | Sort-Object)) { $out += ("    {0,-14} {1}" -f $k, $tally[$k]) }
    $note = "$total marker(s) across $($tally.Keys.Count) task id(s) in $($files.Count) file(s) under $($present -join ', ')"
    return (New-Result 'todo' 'TODO(Tx.y) census (informational)' 'INFO' $out $note)
}

# ── dispatch ─────────────────────────────────────────────────────────────────
$Registry = [ordered]@{
    'g7'         = { Invoke-GateG7 }
    'g4'         = { Invoke-GateG4 }
    'g2'         = { Invoke-GateG2 }
    'ids'        = { Invoke-GateIds }
    'sdk'        = { Invoke-GateSdk }
    'purity'     = { Invoke-GatePurity }
    'transport'  = { Invoke-GateTransport }
    'notes'      = { Invoke-GateNotes }
    'batchstate' = { Invoke-GateBatchState }
    'keepercap'  = { Invoke-GateKeeperCap }
    'send'       = { Invoke-GateSend }
    'seal_le'    = { Invoke-GateSealLe }
    'todo'       = { Invoke-GateTodo }
}

$requested = @()
if (-not $Gate -or $Gate.Count -eq 0) { $requested = @($Registry.Keys) }
else {
    foreach ($g in $Gate) {
        $key = $g.ToLowerInvariant().TrimStart('-')
        if ($key -eq 'all') { $requested = @($Registry.Keys); break }
        if ($key -eq 'help' -or $key -eq '?') {
            Write-Host "gates.ps1 [$(($Registry.Keys) -join '|')|all] [-Strict]   (default: all)"
            Write-Host "  -Strict  a match in a comment fails too (literal 'string must not appear')"
            exit 0
        }
        if (-not $Registry.Contains($key)) {
            Write-Host "gates.ps1: unknown gate '$g'. Known: $(($Registry.Keys) -join ', '), all" -ForegroundColor Red
            exit 2
        }
        $requested += $key
    }
}
$requested = @($requested | Select-Object -Unique)

Write-Host ''
Write-Host 'Aphotic x Hashi — golden-rule gates' -ForegroundColor Cyan
Write-Host "  repo   : $RepoRoot"
Write-Host "  mode   : $(if ($Strict) { 'STRICT (comment mentions fail)' } else { 'default (comment mentions are notes)' })"
Write-Host ''

$results = @()
foreach ($key in $requested) {
    $r = & $Registry[$key]
    $results += $r

    $color = 'Gray'
    if ($r.Status -eq 'PASS') { $color = 'Green' }
    elseif ($r.Status -eq 'FAIL') { $color = 'Red' }
    elseif ($r.Status -eq 'SKIP') { $color = 'Yellow' }
    elseif ($r.Status -eq 'INFO') { $color = 'Cyan' }

    Write-Host ("[{0}] {1,-11} {2}" -f $r.Status.PadRight(4), $r.Name, $r.Title) -ForegroundColor $color
    if ($r.Note) { Write-Host ("       {0}" -f $r.Note) -ForegroundColor DarkGray }

    if ($r.Status -eq 'FAIL') {
        foreach ($h in $r.Hits) {
            $text = $h.Text
            if ($text.Length -gt 140) { $text = $text.Substring(0, 137) + '...' }
            Write-Host ("    {0}:{1}: {2}" -f $h.Rel, $h.Line, $text) -ForegroundColor Red
        }
    }
    elseif ($r.Status -eq 'INFO') {
        foreach ($h in $r.Hits) { Write-Host $h -ForegroundColor DarkCyan }
    }

    foreach ($n in $r.Notes) {
        $text = $n.Text
        if ($text.Length -gt 120) { $text = $text.Substring(0, 117) + '...' }
        Write-Host ("    note {0}:{1}: {2}" -f $n.Rel, $n.Line, $text) -ForegroundColor DarkGray
    }
}

$failCount = @($results | Where-Object { $_.Status -eq 'FAIL' }).Count
$passCount = @($results | Where-Object { $_.Status -eq 'PASS' }).Count
$skipCount = @($results | Where-Object { $_.Status -eq 'SKIP' }).Count

Write-Host ''
Write-Host ("  {0} PASS · {1} FAIL · {2} SKIP" -f $passCount, $failCount, $skipCount) -ForegroundColor $(if ($failCount -gt 0) { 'Red' } else { 'Green' })
if ($skipCount -gt 0) {
    Write-Host '  (SKIP is NOT green — each one above states what was not checked and why.)' -ForegroundColor Yellow
}
Write-Host ''

if ($failCount -gt 0) { exit 1 }
exit 0
